# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-14 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180110_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u8bfe\u7a0bID'),
        ),
    ]
